import { describe, expect, it } from 'vitest'
import { click, fillOrder, renderApp, settle } from '@/test/ui'

describe('Meal statistics view', () => {
  it('shows an empty state then counts pending/completed orders but excludes drafts and cancellations', async () => {
    const { wrapper, router } = await renderApp('/statistics')
    await settle()
    expect(wrapper.text()).toContain('目前沒有已送出訂單的統計資料')
    await router.push('/orders/add')
    await settle()
    await fillOrder(wrapper)
    await click(wrapper, '儲存草稿')
    await settle()
    await router.push('/statistics')
    await settle()
    expect(wrapper.find('table').exists()).toBe(false)
    await router.push('/')
    await settle()
    await click(wrapper, '送出')
    await settle()
    await router.push('/statistics')
    await settle()
    expect(wrapper.get('tbody').text()).toContain('Pizza')
    expect(wrapper.get('tfoot').text()).toContain('500 元')
    expect(wrapper.text()).toContain('統計來自 1 筆')
    await router.push('/')
    await settle()
    await click(wrapper, '取消')
    await settle()
    await router.push('/statistics')
    await settle()
    expect(wrapper.find('table').exists()).toBe(false)
  })
})
