import { describe, expect, it, vi } from 'vitest'
import { orderService } from '@/services/orderService'
import { click, fillOrder, renderApp, settle } from '@/test/ui'

async function draft() {
  const app = await renderApp('/orders/add')
  await settle()
  await fillOrder(app.wrapper)
  await click(app.wrapper, '儲存草稿')
  expect(app.wrapper.get('button[type="submit"]').attributes('disabled')).toBeDefined()
  await settle()
  await vi.waitFor(() => expect(app.router.currentRoute.value.name).toBe('order-detail'))
  await settle()
  expect(app.wrapper.text()).toContain('草稿')
  return app
}

describe('Order views integration', () => {
  it('creates, edits, submits and completes a draft through real routed controls', async () => {
    const { wrapper, router, orders } = await draft()
    const id = router.currentRoute.value.params.id
    expect(wrapper.text()).toContain('500 元')
    await wrapper.get('.status-actions a').trigger('click')
    await vi.waitFor(() => expect(router.currentRoute.value.name).toBe('order-edit'))
    await settle()
    await wrapper.get('.qty-input').setValue(3)
    await wrapper.get('.note-input').setValue('不要辣')
    await click(wrapper, '儲存並送出')
    await settle()
    await settle()
    expect(router.currentRoute.value.params.id).toBe(id)
    expect(wrapper.text()).toContain('處理中')
    expect(wrapper.text()).toContain('750 元')
    expect(wrapper.text()).toContain('不要辣')
    await click(wrapper, '✓ 標記完成')
    await settle()
    expect(wrapper.text()).toContain('已完成')
    expect(wrapper.find('.status-actions').exists()).toBe(false)
    expect(orders.orders[0]?.status).toBe('completed')
    await router.push(`/orders/${id}/edit`)
    await settle()
    expect(wrapper.text()).toContain('此訂單無法編輯')
    expect(wrapper.find('form').exists()).toBe(false)
  })

  it('failed draft creation retains form input and route, shows error, and can be retried', async () => {
    const { wrapper, router, toast } = await renderApp('/orders/add')
    await settle()
    await fillOrder(wrapper)
    vi.spyOn(orderService, 'createOrder').mockRejectedValueOnce(new Error('建立失敗'))
    await click(wrapper, '儲存草稿')
    await settle()
    expect(router.currentRoute.value.name).toBe('order-add')
    expect(wrapper.get('.note-input').element).toHaveProperty('value', '少辣')
    expect(wrapper.get('button[type="submit"]').attributes('disabled')).toBeUndefined()
    expect(toast.toasts.value.at(-1)).toMatchObject({ type: 'error', message: '建立失敗' })
    expect(toast.toasts.value.some((entry) => entry.type === 'success')).toBe(false)
    await click(wrapper, '儲存草稿')
    await settle()
    expect(router.currentRoute.value.name).toBe('order-detail')
  })

  it('failed save-and-submit does not submit or navigate when updating the draft fails', async () => {
    const { wrapper, router, orders, toast } = await draft()
    await router.push(`/orders/${orders.orders[0]!.id}/edit`)
    await settle()
    const submit = vi.spyOn(orderService, 'submitOrder')
    vi.spyOn(orderService, 'updateOrder').mockRejectedValueOnce(new Error('更新失敗'))
    await click(wrapper, '儲存並送出')
    await settle()
    expect(router.currentRoute.value.name).toBe('order-edit')
    expect(submit).not.toHaveBeenCalled()
    expect(orders.orders[0]?.status).toBe('draft')
    expect(toast.toasts.value.at(-1)).toMatchObject({ type: 'error', message: '更新失敗' })
  })

  it('a rejected detail transition keeps the draft editable and restores action buttons', async () => {
    const { wrapper, orders, toast } = await draft()
    vi.spyOn(orderService, 'submitOrder').mockRejectedValueOnce(new Error('送出失敗'))
    await click(wrapper, '送出訂單')
    await settle()
    expect(orders.orders[0]?.status).toBe('draft')
    expect(wrapper.get('.status-actions button').attributes('disabled')).toBeUndefined()
    expect(toast.toasts.value.at(-1)).toMatchObject({ type: 'error', message: '送出失敗' })
  })

  it('list filters, reset, navigation, status actions and confirmed deletion update rendered rows', async () => {
    const { wrapper, router, orders } = await draft()
    await router.push('/')
    await settle()
    await wrapper.get('input[type="search"]').setValue('does-not-match')
    expect(wrapper.text()).toContain('無符合條件的訂單')
    await click(wrapper, '重置篩選')
    expect(wrapper.findAll('tbody tr')).toHaveLength(1)
    await click(wrapper, '送出')
    await settle()
    expect(wrapper.get('tbody').text()).toContain('處理中')
    await click(wrapper, '取消')
    await settle()
    expect(wrapper.get('tbody').text()).toContain('已取消')
    expect(wrapper.get('tbody').text()).not.toContain('編輯')
    const confirm = vi.spyOn(window, 'confirm').mockReturnValue(false)
    await click(wrapper, '刪除')
    expect(orders.orders).toHaveLength(1)
    confirm.mockReturnValue(true)
    vi.spyOn(orderService, 'deleteOrder').mockRejectedValueOnce(new Error('刪除失敗'))
    await click(wrapper, '刪除')
    await settle()
    expect(wrapper.findAll('tbody tr')).toHaveLength(1)
    await click(wrapper, '刪除')
    await settle()
    expect(wrapper.text()).toContain('目前沒有訂單')
    expect(orders.orders).toHaveLength(0)
  })
})
